### Examine the corrected or uncorrected counts

In [1]:
import scanpy as sc 
import numpy as np

### scVI adata

In [3]:
%%time
scvi_adata = sc.read_h5ad("04A_scvi_sc_sn_combined.h5ad")
scvi_adata

In [7]:
scvi_adata.layers['scvi_normalized'].min()

2.256144e-05

In [8]:
scvi_adata.layers['scvi_normalized'].sum(axis = 1)

array([100000.02, 100000.  , 100000.01, ...,  99999.99,  99999.99,
       100000.02], dtype=float32)

### CellANOVA adata

In [4]:
%%time
CellANOVA_adata = sc.read_h5ad("04B_post_CellANOVA.h5ad")
CellANOVA_adata

In [13]:
CellANOVA_adata.layers['denoised'].min()

-9.323021916899265

In [16]:
CellANOVA_adata.layers['denoised'].sum(axis = 1)

array([ 86.06459883, 895.16390228, 111.41285211, ...,  97.46871379,
        92.13585961, -81.12126433])

### Harmony adata

In [22]:
adata = sc.read_h5ad("03B_sc_sn_adata.h5ad")
adata

AnnData object with n_obs × n_vars = 121628 × 16115
    obs: 'age', 'donor_id', 'sex', 'region', 'cell_type', 'consistent_cell_type', 'study', 'technology', 'cell_or_nuclei', 'tech_plus_study', '_scvi_batch', '_scvi_labels', 'leiden_scVI', 'scvi_cell_type'
    obsm: 'X_scVI', 'X_umap', '_scvi_extra_categorical_covs'
    layers: 'counts'

In [25]:
adata.X.sum(axis = 1)

matrix([[27470.],
        [18516.],
        [17130.],
        ...,
        [ 2826.],
        [  874.],
        [ 2055.]])

In [17]:
harmony_adata = sc.read_h5ad("04C_harmony_integrated_adata.h5ad")
harmony_adata

AnnData object with n_obs × n_vars = 121628 × 16115
    obs: 'age', 'donor_id', 'sex', 'region', 'cell_type', 'consistent_cell_type', 'study', 'technology', 'cell_or_nuclei', 'tech_plus_study', '_scvi_batch', '_scvi_labels', 'leiden_scVI', 'scvi_cell_type'
    var: 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'cell_or_nuclei_colors', 'consistent_cell_type_colors', 'donor_id_colors', 'hvg', 'log1p', 'neighbors', 'pca', 'study_colors', 'technology_colors', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_scVI', 'X_umap', 'X_umap_harmony', '_scvi_extra_categorical_covs'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'

In [20]:
harmony_adata.X.sum(axis = 1)
harmony_adata.X.sum(axis = 1)

matrix([[1337.50221222],
        [1365.31669663],
        [1251.22230417],
        ...,
        [1151.21556308],
        [1024.29908227],
        [1180.39597743]])